#!/bin/bash
# ============================================
# Hermes Assessment Environment Entrypoint
# ============================================
# This script:
# 1. Configures Git for the candidate
# 2. Initializes the workspace repository
# 3. Starts telemetry sidecar (background)
# 4. Starts auto-commit daemon (background)
# 5. Launches code-server
# ============================================

set -e

echo "🚀 Starting Hermes Assessment Environment..."
echo "============================================"

# ============================================
# 1. Configure Git
# ============================================
echo "📝 Configuring Git..."
git config --global user.name "${GIT_USER_NAME:-Candidate}"
git config --global user.email "${GIT_USER_EMAIL:-candidate@assessment.local}"
git config --global init.defaultBranch main
git config --global core.autocrlf input

# ============================================
# 2. Initialize workspace
# ============================================
if [ ! -d "/workspace/.git" ]; then
    echo "📁 Initializing workspace..."
    cd /workspace

    echo "✨ Initializing workspace..."
    # Initialize a fresh git repo to track the candidate's work locally
    git init
    
    # Create initial README if workspace is empty (it shouldn't be now)
    if [ ! -f "README.md" ]; then
        echo "# Assessment Workspace" > README.md
        echo "Your assessment environment is ready!" >> README.md
    fi
    
    # Configure git user
    git config user.email "${GIT_USER_EMAIL:-candidate@hermes.com}"
    git config user.name "${GIT_USER_NAME:-Candidate}"
    
    # Ensure generated files are tracked
    git add -A 2>/dev/null || true
    git commit -m "Initial workspace setup" 2>/dev/null || true
fi

# ============================================
# 2b. Generate .env.local from environment variables
# This replaces the need for the candidate to run scripts/provision-key.js manually
# ============================================
echo "🔑 Provisioning credentials to .env.local..."
ENV_FILE="/workspace/.env.local"

# Start fresh or append? Usually fresh for provisioning.
echo "# Auto-generated by Hermes Assessment Environment" > "$ENV_FILE"

# List of keys to inject if present in environment
KEYS=(
    "CANDIDATE_ID"
    "SESSION_ID"
    "SUPABASE_URL"
    "SUPABASE_ANON_KEY"
    "SUPABASE_PRIVATE_KEY"
    "SUPABASE_SERVICE_ROLE_KEY"
    "GEMINI_BASE_URL"
    "GOOGLE_BASE_URL"
    "GOOGLE_API_KEY"
    "QUARTERMASTER_API_URL"
)

COUNT=0
for KEY in "${KEYS[@]}"; do
    if [ -n "${!KEY}" ]; then
        echo "$KEY=${!KEY}" >> "$ENV_FILE"
        COUNT=$((COUNT+1))
    fi
done

if [ "$COUNT" -gt 0 ]; then
    echo "   ✓ Injected $COUNT credentials into .env.local"
else
    echo "   ⚠️  No credentials found in environment to inject"
    echo "      ensure CANDIDATE_ID, SUPABASE_URL, etc., are passed to the container."
fi

# ============================================
# 3. Start telemetry sidecar (background)
# ============================================
if [ -n "$TELEMETRY_URL" ] && [ -n "$SESSION_ID" ]; then
    echo "📊 Starting telemetry sidecar..."
    /usr/local/bin/telemetry-sidecar.sh &
    TELEMETRY_PID=$!
    echo "   Telemetry PID: $TELEMETRY_PID"
else
    echo "⚠️  Telemetry disabled (TELEMETRY_URL or SESSION_ID not set)"
fi

# ============================================
# 4. Configure Claude Code settings (inject env vars)
# ============================================
if [ -f "/home/coder/.claude/settings.local.json" ]; then
    echo "🔧 Configuring Claude Code with runtime environment..."
    
    # Replace environment variable placeholders in Claude settings
    sed -i "s|\${TELEMETRY_URL:-}|${TELEMETRY_URL:-}|g" /home/coder/.claude/settings.local.json
    sed -i "s|\${SESSION_ID:-}|${SESSION_ID:-}|g" /home/coder/.claude/settings.local.json
    sed -i "s|\${CANDIDATE_ID:-}|${CANDIDATE_ID:-}|g" /home/coder/.claude/settings.local.json
    
    echo "   ✓ Claude Code configured"
else
    echo "⚠️  Claude Code settings not found at /home/coder/.claude/settings.local.json"
fi

# ============================================
# 5. Start auto-commit daemon (background)
# ============================================
echo "⏰ Starting auto-commit daemon (every ${AUTO_COMMIT_INTERVAL:-120}s)..."
/usr/local/bin/auto-commit.sh &
AUTO_COMMIT_PID=$!
echo "   Auto-commit PID: $AUTO_COMMIT_PID"

# ============================================
# 6. Log startup info
# ============================================
echo "============================================"
echo "✅ Environment ready!"
echo "📝 Candidate ID: ${CANDIDATE_ID:-not-set}"
echo "🔗 Session ID: ${SESSION_ID:-not-set}"
echo "🌐 Telemetry URL: ${TELEMETRY_URL:-not-set}"
echo "⏰ Auto-commit interval: ${AUTO_COMMIT_INTERVAL:-120}s"
echo "============================================"

# ============================================
# 7. Start code-server
# ============================================
echo "🖥️  Starting code-server on 0.0.0.0:8080..."
exec code-server --bind-addr 0.0.0.0:8080 --auth none /workspace
