#!/bin/bash
# ============================================
# Hermes Assessment Environment Entrypoint
# ============================================
# CRITICAL: Start code-server FIRST for fast port binding
# Then run setup tasks in background
# ============================================

echo "🚀 Starting Hermes Assessment Environment..."
echo "============================================"

# Display build version
if [ -f "/home/coder/.hermes-version.json" ]; then
    echo "📦 Container Version:"
    cat /home/coder/.hermes-version.json | python3 -c 'import sys, json; d=json.load(sys.stdin); print("   Built: " + d["built_at"])'
    echo "============================================"
fi


# Ensure Supabase Service Key is available
export SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-$SUPABASE_SERVICE_ROLE_KEY}

# Disable file watchers to reduce CPU usage
export CHOKIDAR_USEPOLLING=false
export WATCHPACK_POLLING=false
export NEXT_TELEMETRY_DISABLED=1

# ============================================
# PERFORMANCE LOGGING
# ============================================
log_metric() {
    local name="$1"
    local duration="$2"
    local extra="${3:-}"
    echo "METRIC::${name}::${duration}ms ${extra}"
}

measure_step() {
    local step_name="$1"
    shift
    local start_ts=$(date +%s%3N)
    "$@"
    local ret=$?
    local end_ts=$(date +%s%3N)
    local duration=$((end_ts - start_ts))
    log_metric "$step_name" "$duration"
    return $ret
}

# ============================================
# SETUP FUNCTIONS
# ============================================

setup_claude_auth() {
    # Deprecated: Claude Auth is now handled via direct API in the backend
    echo "🔒 Claude Auth (Deprecated)"
}

setup_claude_wrapper() {
    # Deprecated: Claude Code wrapper is no longer used
    echo "🛡️  Claude Wrapper (Deprecated)"
}

setup_bash_config() {
    # 3. Bash aliases and Welcome Message
    cat >> /home/coder/.bashrc << 'BASHRC'
export PATH="$HOME/.local/bin:$PATH"
alias claude='claude-code'
alias ask='claude-code'

# Welcome Message
echo -e "\n\033[1;34m🚀 Welcome to Hermes Assessment Environment!\033[0m"
echo -e "\033[0;32m------------------------------------------\033[0m"
echo -e "To start your application, run: \033[1;33mnpm run dev\033[0m"
echo -e "To preview your app visually, click the \033[1;34m'Preview App'\033[0m button at the top of the IDE."
echo -e "Your app will be available on \033[1;36mport 3000\033[0m by default."
echo -e "\033[0;32m------------------------------------------\033[0m\n"
BASHRC

    # 4. Interactive Mode logging hooks
    mkdir -p /home/coder/.claude/hooks
    if [ -f "/usr/local/bin/log-prompt.sh" ]; then
        cp /usr/local/bin/log-prompt.sh /home/coder/.claude/hooks/log-prompt.sh
        chmod +x /home/coder/.claude/hooks/log-prompt.sh
    fi
}

setup_git() {
    # 5. Git & Workspace Initialization
    echo "📝 Configuring Git..."
    git config --global user.name "${GIT_USER_NAME:-Candidate}"
    git config --global user.email "${GIT_USER_EMAIL:-candidate@assessment.local}"
    git config --global init.defaultBranch main

    if [ ! -d "/workspace/.git" ]; then
        echo "📁 Initializing workspace..."
        cd /workspace
        git init
        git config user.email "${GIT_USER_EMAIL:-candidate@hermes.com}"
        git config user.name "${GIT_USER_NAME:-Candidate}"
        git add -A 2>/dev/null || true
        git commit -m "Initial workspace setup" 2>/dev/null || true
    fi
}

setup_env_local() {
    # 6. Generate .env.local
    echo "🔑 Provisioning credentials to .env.local..."
    ENV_FILE="/workspace/.env.local"
    echo "# Auto-generated by Hermes Assessment Environment" > "$ENV_FILE"
    KEYS=("CANDIDATE_ID" "SESSION_ID" "NEXT_PUBLIC_SUPABASE_URL" "NEXT_PUBLIC_SUPABASE_ANON_KEY" "GEMINI_BASE_URL" "GOOGLE_BASE_URL" "GOOGLE_API_KEY" "QUARTERMASTER_API_URL")

    for KEY in "${KEYS[@]}"; do
        if [ -n "${!KEY}" ]; then
            echo "$KEY=${!KEY}" >> "$ENV_FILE"
        fi
    done
    
    # Force development servers to bind to all interfaces for external access
    echo "HOST=0.0.0.0" >> "$ENV_FILE"
    echo "PORT=3000" >> "$ENV_FILE"
}

setup_telemetry() {
    # 7. Start Telemetry Sidecar
    if [ -n "$TELEMETRY_URL" ] && [ -n "$SESSION_ID" ]; then
        echo "📊 Starting telemetry sidecar..."
        /usr/local/bin/telemetry-sidecar.sh &
    fi
}

start_dev_server() {
    # 8. Auto-start the development server
    echo "🚀 Starting development server..."
    cd /workspace
    # Start npm run dev in the background, redirect output to a log file
    nohup npm run dev > /workspace/.dev-server.log 2>&1 &
    echo "✅ Development server starting on port 3000"
    echo "   Logs: /workspace/.dev-server.log"

    # Pre-compile main routes in background to speed up first access
    (
        echo "⏳ Waiting for dev server to be ready..."
        # Wait for Next.js to be ready (max 30s)
        for i in {1..30}; do
            if curl -s http://localhost:3000 > /dev/null 2>&1; then
                echo "✅ Dev server ready, pre-compiling routes..."
                # Pre-compile main routes
                curl -s http://localhost:3000 > /dev/null 2>&1 &
                curl -s http://localhost:3000/insights > /dev/null 2>&1 &
                echo "✅ Routes pre-compilation started"
                break
            fi
            sleep 1
        done
    ) &
}

# ============================================
# BACKGROUND SETUP FUNCTION
# Runs AFTER code-server starts
# ============================================
run_background_setup() {
    echo "⏳ Running background setup..."

    # Fix workspace permissions - ULTRA-OPTIMIZED
    # Only fix directories that ACTUALLY need write access during runtime
    # Source code directories (app, components, lib, utils, tests, scripts, supabase) are READ-ONLY
    echo "🔧 Fixing workspace permissions..."
    (
        # Fix top-level directory
        sudo chown coder:coder /workspace 2>/dev/null || true
        
        # Only fix directories that need WRITE access during runtime/testing
        # .next - Next.js build cache
        # .vitest-cache - Vitest cache
        # .git - Git operations during testing
        for dir in .next .vitest-cache .git; do
            if [ -d "/workspace/$dir" ]; then
                sudo chown -R coder:coder "/workspace/$dir" 2>/dev/null || true
            fi
        done
        
        # Fix root-level files that need write access
        sudo chown coder:coder /workspace/test-results.json 2>/dev/null || true
        sudo chown coder:coder /workspace/.env* 2>/dev/null || true
        sudo chown coder:coder /workspace/*.log 2>/dev/null || true
        sudo chown coder:coder /workspace/tsconfig.tsbuildinfo 2>/dev/null || true
        
        # Note: node_modules/.vite is handled separately in run-tests.sh
        # Source code dirs (app, components, lib, utils, tests, scripts, supabase) are read-only - no chown needed
    ) &

    measure_step "setup_claude_auth" setup_claude_auth
    measure_step "setup_claude_wrapper" setup_claude_wrapper
    measure_step "setup_bash_config" setup_bash_config
    measure_step "setup_git" setup_git
    measure_step "setup_env_local" setup_env_local
    measure_step "setup_telemetry" setup_telemetry
    measure_step "start_dev_server" start_dev_server

    # Final ownership check
    chown -R coder:coder /home/coder/.claude 2>/dev/null || true

    echo "✅ Background setup complete!"
}

# ============================================
# MAIN: Start code-server IMMEDIATELY
# ============================================
echo "🖥️  Starting code-server on 0.0.0.0:8080..."

# Run background setup after code-server starts (non-blocking)
run_background_setup &

# Start code-server (this blocks and keeps container running)
exec code-server --bind-addr 0.0.0.0:8080 --auth none --disable-workspace-trust /workspace
