#!/bin/bash
# ============================================
# Hermes Assessment Environment Entrypoint
# ============================================
# CRITICAL: Start code-server FIRST for fast port binding
# Then run setup tasks in background
# ============================================

echo "🚀 Starting Hermes Assessment Environment..."
echo "============================================"

# Display build version
if [ -f "/home/coder/.hermes-version.json" ]; then
    echo "📦 Container Version:"
    cat /home/coder/.hermes-version.json | node -e 'const fs = require("fs"); const d = JSON.parse(fs.readFileSync(0, "utf-8")); console.log("   Built: " + d.built_at)'
    echo "============================================"
fi


# Ensure Supabase Service Key is available
export SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-$SUPABASE_SERVICE_ROLE_KEY}


export NEXT_TELEMETRY_DISABLED=1

# ============================================
# PERFORMANCE LOGGING
# ============================================
log_metric() {
    local name="$1"
    local duration="$2"
    local extra="${3:-}"
    echo "METRIC::${name}::${duration}ms ${extra}"
}

measure_step() {
    local step_name="$1"
    shift
    local start_ts=$(date +%s%3N)
    "$@"
    local ret=$?
    local end_ts=$(date +%s%3N)
    local duration=$((end_ts - start_ts))
    log_metric "$step_name" "$duration"
    return $ret
}

# ============================================
# SETUP FUNCTIONS
# ============================================

setup_claude_auth() {
    # Deprecated: Claude Auth is now handled via direct API in the backend
    echo "🔒 Claude Auth (Deprecated)"
}

setup_claude_wrapper() {
    # Deprecated: Claude Code wrapper is no longer used
    echo "🛡️  Claude Wrapper (Deprecated)"
}

setup_bash_config() {
    # 3. Bash aliases and Welcome Message
    cat >> /home/coder/.bashrc << 'BASHRC'
export PATH="$HOME/.local/bin:$PATH"
alias claude='claude-code'
alias ask='claude-code'


BASHRC

    # 4. Interactive Mode logging hooks
    mkdir -p /home/coder/.claude/hooks
    if [ -f "/usr/local/bin/log-prompt.sh" ]; then
        cp /usr/local/bin/log-prompt.sh /home/coder/.claude/hooks/log-prompt.sh
        chmod +x /home/coder/.claude/hooks/log-prompt.sh
    fi
}

setup_git() {
    # 5. Git & Workspace Initialization
    echo "📝 Configuring Git..."
    git config --global user.name "${GIT_USER_NAME:-Candidate}"
    git config --global user.email "${GIT_USER_EMAIL:-candidate@assessment.local}"
    git config --global init.defaultBranch main

    if [ ! -d "/workspace/.git" ]; then
        echo "📁 Initializing workspace..."
        cd /workspace
        git init
        git config user.email "${GIT_USER_EMAIL:-candidate@hermes.com}"
        git config user.name "${GIT_USER_NAME:-Candidate}"
        git add -A 2>/dev/null || true
        git commit -m "Initial workspace setup" 2>/dev/null || true
    fi
}

setup_env_local() {
    # 6. Generate .env.local
    echo "🔑 Provisioning credentials to .env.local..."
    ENV_FILE="/workspace/.env.local"
    echo "# Auto-generated by Hermes Assessment Environment" > "$ENV_FILE"
    KEYS=("CANDIDATE_ID" "SESSION_ID" "NEXT_PUBLIC_SUPABASE_URL" "NEXT_PUBLIC_SUPABASE_ANON_KEY" "GEMINI_BASE_URL" "GOOGLE_BASE_URL" "GOOGLE_API_KEY" "QUARTERMASTER_API_URL")

    for KEY in "${KEYS[@]}"; do
        if [ -n "${!KEY}" ]; then
            echo "$KEY=${!KEY}" >> "$ENV_FILE"
        fi
    done

    # Force development servers to bind to all interfaces for external access
    echo "HOST=0.0.0.0" >> "$ENV_FILE"
    echo "PORT=3000" >> "$ENV_FILE"
}

start_dev_server() {
    # 8. Auto-start the development server
    echo "🚀 Starting development server..."
    cd /workspace
    # Start npm run dev in the background, redirect output to a log file
    # Start next dev directly (avoids polling overhead from package.json script)
    nohup npx next dev --turbo > /workspace/.dev-server.log 2>&1 &
    echo "✅ Development server starting on port 3000"
    echo "   Logs: /workspace/.dev-server.log"
}

# ============================================
# BACKGROUND SETUP FUNCTION
# Runs AFTER code-server starts
# ============================================
run_background_setup() {
    echo "⏳ Running background setup..."

    # Fix workspace permissions - simplified
    echo "🔧 Fixing workspace permissions..."
    sudo chown -R coder:coder /workspace/.next /workspace/.env* 2>/dev/null || true &
    
    measure_step "setup_claude_auth" setup_claude_auth
    measure_step "setup_claude_wrapper" setup_claude_wrapper
    measure_step "setup_bash_config" setup_bash_config
    measure_step "setup_git" setup_git
    measure_step "setup_env_local" setup_env_local
    measure_step "start_dev_server" start_dev_server


    # Final ownership check
    chown -R coder:coder /home/coder/.claude 2>/dev/null || true

    echo "✅ Background setup complete!"
}

# ============================================
# MAIN: Start code-server
# ============================================

# CRITICAL: Ensure settings are valid and owned by coder BEFORE starting
# This prevents code-server from loading default settings (ignoring our config)
check_settings() {
    SETTINGS_PATH="/home/coder/.local/share/code-server/User/settings.json"
    BACKUP_PATH="/home/coder/.local/share/code-server/User/settings.json.bak"
    
    echo "⚙️  Enforcing default settings..."
    # Always overwrite with enforced settings to prevent persistence of theme changes etc.
    if [ -f "$BACKUP_PATH" ]; then
         cp "$BACKUP_PATH" "$SETTINGS_PATH"
         sudo chown coder:coder "$SETTINGS_PATH"
         echo "✅ Settings enforced from backup"
    else
         echo "⚠️  Backup settings missing, skipping enforcement"
    fi

    # Force remove GitHub Copilot extensions directly in the entrypoint
    # This runs synchronously BEFORE code-server starts to prevent them from loading
    echo "🚫 Removing GitHub Copilot extensions..."
    rm -rf /home/coder/.local/share/code-server/extensions/GitHub.copilot* 2>/dev/null || true
    rm -rf /home/coder/.local/share/code-server/extensions/GitHub.copilot-chat* 2>/dev/null || true
}

echo "🛠️  Verifying configuration..."
check_settings

# Fix workspace permissions synchronously for the root folder
# This ensures code-server can actually read the workspace directory on launch
echo "🔧 Fixing workspace permissions..."
sudo chown coder:coder /workspace
# Restore workspace if completely empty (emergency fallback)
# Restore check removed as template is no longer valid
# if [ ! -f "/workspace/package.json" ] && [ -d "/usr/local/share/workspace-template" ]; then
#     echo "📦 Restoring workspace files..."
#     cp -n -R /usr/local/share/workspace-template/. /workspace/ || true
# fi

echo "🖥️  Starting code-server on 0.0.0.0:8080..."

# Run remaining heavy setup tasks in background
run_background_setup &

# Start code-server (this blocks and keeps container running)
# Open the workspace folder
exec code-server --bind-addr 0.0.0.0:8080 --auth none --disable-workspace-trust /workspace

