#!/bin/bash
# ============================================
# Hermes Assessment Execution Environment Entrypoint
# Pure Node.js Edition - NO IDE
# ============================================

echo "🚀 Starting Hermes Assessment Environment (Execution Only)..."
echo "============================================"

# Display build version
if [ -f "/home/coder/.hermes-version.json" ]; then
    echo "📦 Container Version:"
    cat /home/coder/.hermes-version.json | node -e 'const fs = require("fs"); const d = JSON.parse(fs.readFileSync(0, "utf-8")); console.log("   Built: " + d.built_at + " | Base: " + d.base)'
    echo "============================================"
fi

# Ensure Supabase Service Key is available
export SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-$SUPABASE_SERVICE_ROLE_KEY}
export NEXT_TELEMETRY_DISABLED=1

# ============================================
# SETUP FUNCTIONS
# ============================================

setup_bash_config() {
    mkdir -p /home/coder/.claude/hooks
    if [ -f "/usr/local/bin/log-prompt.sh" ]; then
        cp /usr/local/bin/log-prompt.sh /home/coder/.claude/hooks/log-prompt.sh
        chmod +x /home/coder/.claude/hooks/log-prompt.sh
    fi
}

setup_git() {
    echo "📝 Configuring Git..."
    git config --global user.name "${GIT_USER_NAME:-Candidate}"
    git config --global user.email "${GIT_USER_EMAIL:-candidate@assessment.local}"
    git config --global init.defaultBranch main

    if [ ! -d "/workspace/.git" ]; then
        echo "📁 Initializing workspace..."
        cd /workspace
        git init
        git config user.email "${GIT_USER_EMAIL:-candidate@hermes.com}"
        git config user.name "${GIT_USER_NAME:-Candidate}"
        git add -A 2>/dev/null || true
        git commit -m "Initial workspace setup" 2>/dev/null || true
    fi
}

setup_env_local() {
    echo "🔑 Provisioning credentials to .env.local..."
    ENV_FILE="/workspace/.env.local"
    echo "# Auto-generated by Hermes Assessment Environment" > "$ENV_FILE"
    KEYS=("CANDIDATE_ID" "SESSION_ID" "NEXT_PUBLIC_SUPABASE_URL" "NEXT_PUBLIC_SUPABASE_ANON_KEY" "GEMINI_BASE_URL" "GOOGLE_BASE_URL" "GOOGLE_API_KEY" "QUARTERMASTER_API_URL")

    for KEY in "${KEYS[@]}"; do
        if [ -n "${!KEY}" ]; then
            echo "$KEY=${!KEY}" >> "$ENV_FILE"
        fi
    done

    echo "HOST=0.0.0.0" >> "$ENV_FILE"
    echo "PORT=8080" >> "$ENV_FILE"
}

# ============================================
# MAIN
# ============================================

echo "🛠️  Verifying configuration..."

# Block Copilot domains at network level (optional, assuming /etc/hosts is writable)
if [ -w "/etc/hosts" ]; then
    echo "🔒 Blocking Copilot domains..."
    if ! grep -q "copilot-proxy.githubusercontent.com" /etc/hosts 2>/dev/null; then
        sudo bash -c 'cat >> /etc/hosts << EOF
127.0.0.1 copilot-proxy.githubusercontent.com
127.0.0.1 api.githubcopilot.com
127.0.0.1 default.exp-tas.com
EOF'
    fi
fi

# Fix workspace permissions
echo "🔧 Fixing workspace permissions..."
sudo chown -R coder:coder /workspace/.next /workspace/.env* 2>/dev/null || true

# Run setup tasks
setup_bash_config
setup_git
setup_env_local
chown -R coder:coder /home/coder/.claude 2>/dev/null || true

echo "✅ Environment setup complete!"

echo "============================================"
echo "🚀 Starting development server on 0.0.0.0:8080..."
echo "============================================"

# Navigate to workspace
cd /workspace

# Start npm run dev. 
# We use exec so it replaces the shell process and receives signals (SIGTERM) correctly.
export PORT=8080
exec npm run dev
