#!/bin/bash
# ============================================
# Hermes Assessment Environment Entrypoint
# Minimal Build Edition (Clean code-server)
# ============================================

echo "🚀 Starting Hermes Assessment Environment (Minimal Build)..."
echo "============================================"

# Display build version
if [ -f "/home/coder/.hermes-version.json" ]; then
    echo "📦 Container Version:"
    cat /home/coder/.hermes-version.json | node -e 'const fs = require("fs"); const d = JSON.parse(fs.readFileSync(0, "utf-8")); console.log("   Built: " + d.built_at + " | Base: " + d.base)'
    echo "============================================"
fi

# Ensure Supabase Service Key is available
export SUPABASE_SERVICE_KEY=${SUPABASE_SERVICE_KEY:-$SUPABASE_SERVICE_ROLE_KEY}
export NEXT_TELEMETRY_DISABLED=1

# ============================================
# SETUP FUNCTIONS
# ============================================

setup_bash_config() {
    cat >> /home/coder/.bashrc << 'BASHRC'
export PATH="$HOME/.local/bin:$PATH"
alias claude='claude-code'
alias ask='claude-code'

BASHRC

    mkdir -p /home/coder/.claude/hooks
    if [ -f "/usr/local/bin/log-prompt.sh" ]; then
        cp /usr/local/bin/log-prompt.sh /home/coder/.claude/hooks/log-prompt.sh
        chmod +x /home/coder/.claude/hooks/log-prompt.sh
    fi
}

setup_git() {
    echo "📝 Configuring Git..."
    git config --global user.name "${GIT_USER_NAME:-Candidate}"
    git config --global user.email "${GIT_USER_EMAIL:-candidate@assessment.local}"
    git config --global init.defaultBranch main

    if [ ! -d "/workspace/.git" ]; then
        echo "📁 Initializing workspace..."
        cd /workspace
        git init
        git config user.email "${GIT_USER_EMAIL:-candidate@hermes.com}"
        git config user.name "${GIT_USER_NAME:-Candidate}"
        git add -A 2>/dev/null || true
        git commit -m "Initial workspace setup" 2>/dev/null || true
    fi
}

setup_env_local() {
    echo "🔑 Provisioning credentials to .env.local..."
    ENV_FILE="/workspace/.env.local"
    echo "# Auto-generated by Hermes Assessment Environment" > "$ENV_FILE"
    KEYS=("CANDIDATE_ID" "SESSION_ID" "NEXT_PUBLIC_SUPABASE_URL" "NEXT_PUBLIC_SUPABASE_ANON_KEY" "GEMINI_BASE_URL" "GOOGLE_BASE_URL" "GOOGLE_API_KEY" "QUARTERMASTER_API_URL")

    for KEY in "${KEYS[@]}"; do
        if [ -n "${!KEY}" ]; then
            echo "$KEY=${!KEY}" >> "$ENV_FILE"
        fi
    done

    echo "HOST=0.0.0.0" >> "$ENV_FILE"
    echo "PORT=3000" >> "$ENV_FILE"
}

start_dev_server() {
    echo "🚀 Starting development server..."
    cd /workspace
    nohup npm run dev > /workspace/.dev-server.log 2>&1 &

    (
        echo "🔥 Waiting for Next.js to be ready..."
        for i in {1..60}; do
            if curl -s -f http://localhost:3000/ > /dev/null 2>&1; then
                echo "✅ Next.js is ready!"
                curl -s http://localhost:3000/ > /dev/null
                break
            fi
            [ $((i % 5)) -eq 0 ] && echo "⏳ Waiting for server... ($i/60)"
            sleep 1
        done
    ) &

    echo "✅ Development server started"
}

run_background_setup() {
    echo "⏳ Running background setup..."

    sudo chown -R coder:coder /workspace/.next /workspace/.env* 2>/dev/null || true &

    setup_bash_config
    setup_git
    setup_env_local
    start_dev_server

    chown -R coder:coder /home/coder/.claude 2>/dev/null || true

    echo "✅ Background setup complete!"
}

# ============================================
# MAIN: Setup and Start code-server
# ============================================

echo "🛠️  Verifying configuration..."

# Block Copilot domains at network level (belt and suspenders)
if [ -w "/etc/hosts" ]; then
    echo "🔒 Blocking Copilot domains..."
    if ! grep -q "copilot-proxy.githubusercontent.com" /etc/hosts 2>/dev/null; then
        sudo bash -c 'cat >> /etc/hosts << EOF
127.0.0.1 copilot-proxy.githubusercontent.com
127.0.0.1 api.githubcopilot.com
127.0.0.1 default.exp-tas.com
EOF'
        echo "   ✓ Domains blocked"
    fi
fi

# Fix workspace permissions (only specific files that may be created at runtime)
echo "🔧 Fixing workspace permissions..."
sudo chown -R coder:coder /workspace/.next /workspace/.env* 2>/dev/null || true

# Verify settings are in place
if [ -f "/home/coder/.local/share/code-server/User/settings.json" ]; then
    echo "   ✓ Settings configured"
fi

# Run background setup
run_background_setup &

echo "============================================"
echo "🖥️  Starting code-server on 0.0.0.0:8080..."
echo "============================================"

# Start code-server with strict flags
# --disable-telemetry: No telemetry
# --disable-update-check: No update checks
# --extensions-dir: Point to read-only empty directory
exec code-server \
  --bind-addr 0.0.0.0:8080 \
  --auth none \
  --disable-workspace-trust \
  --disable-getting-started-override \
  --disable-telemetry \
  --disable-update-check \
  --extensions-dir /home/coder/.local/share/code-server/extensions \
  --user-data-dir /home/coder/.local/share/code-server \
  /workspace
