#!/bin/bash
# Quick script to get Aidan's candidate ID and create container

echo "🔍 Looking up your candidate ID..."
echo ""

# You need to run this SQL query in Supabase to get your ID:
echo "=============================================="
echo "Step 1: Get Your Candidate ID"
echo "=============================================="
echo ""
echo "Go to Supabase SQL Editor and run:"
echo ""
echo "SELECT id, email, name FROM candidates WHERE email = 'aidan.nt76@gmail.com';"
echo ""
echo "Copy the 'id' value (it's a UUID like: abc-123-def-456)"
echo ""
echo "=============================================="
echo "Step 2: Run This Command"
echo "=============================================="
echo ""
echo "Once you have your ID, run:"
echo ""
echo "./docker/start-assessment.sh <your-candidate-id>"
echo ""
echo "Example:"
echo "./docker/start-assessment.sh 550e8400-e29b-41d4-a716-446655440000"
echo ""
echo "=============================================="
echo ""
echo "Or, if you want to do it all at once:"
echo ""
echo "1. Set your candidate ID:"
echo "   export MY_CANDIDATE_ID='<paste-your-uuid-here>'"
echo ""
echo "2. Stop test container:"
echo "   docker rm -f hermes-assessment-test-user-123"
echo ""
echo "3. Start your container:"
echo "   ./docker/start-assessment.sh \$MY_CANDIDATE_ID"
echo ""
echo "4. Test it:"
echo "   ./docker/test-environment.sh"
echo ""
echo "5. Visit the IDE:"
echo "   http://localhost:3000/ide (sign in as aidan.nt76@gmail.com)"
echo ""
